env:
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx', '.json']
      paths: [ src ]
rules:
  import/prefer-default-export: 'off'
  import/no-default-export: 'error'
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  max-len: [2, 140, {"ignoreUrls": true}]
  comma-dangle: [0, 'always-multiline']
  import/extensions: 'off'
  import/no-dynamic-require: 0
  indent:  ["error", 4, {"SwitchCase": 1}]