name: "Send notifications to MS Teams channel - on push"

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test sample notification
        uses: ./
        with:
          job_status: ${{ job.status }}
          webhook_url: ${{ secrets.MS_WEBHOOK_URL }}
